services:
  - type: web
    name: mrdot-ecommerce
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_test_YOUR_STRIPE_PUBLISHABLE_KEY_HERE
      - key: STRIPE_SECRET_KEY
        value: sk_test_YOUR_STRIPE_SECRET_KEY_HERE
      - key: JWT_SECRET
        value: mr_dot_super_secret_key_2024_braille_art_platform
      - key: DATA_DIR
        value: ./data
      - key: UPLOADS_DIR
        value: ./uploads
      - key: ADMIN_EMAIL
        value: admin@mrdot.com
      - key: ADMIN_PASSWORD
        value: MrDot2024Admin!
    domains:
      - mrdot-ecommerce.onrender.com 